### ISSUE TITLE
Lightning feedback

### ISSUE THREAD

**Issue by gglerum** [heartmates01/Lightning#1]
Je mag dezelfde scanner her gebruiken, dan hoef je niet meerdere input streams te openen. Je mag dus de scanner op regel 44 op de volgende twee plaatsen hergebruiken:

https://github.com/heartmates01/Lightning/blob/d1fe1f8536373f9aa731c8c1b83999e175e638c6/src/main/java/nl/heartmates01/Main.java#L50
https://github.com/heartmates01/Lightning/blob/d1fe1f8536373f9aa731c8c1b83999e175e638c6/src/main/java/nl/heartmates01/Main.java#L65

Je herhaalt twee keer bijna hetzelfde code block:
https://github.com/heartmates01/Lightning/blob/d1fe1f8536373f9aa731c8c1b83999e175e638c6/src/main/java/nl/heartmates01/Main.java#L48-L62

en

https://github.com/heartmates01/Lightning/blob/d1fe1f8536373f9aa731c8c1b83999e175e638c6/src/main/java/nl/heartmates01/Main.java#L63-L78

Het enige verschil dat ik kan zien is dat de "eenheid" (feet of meters) verschilt. Kun je een manier bedenken waarop je de code zo kunt schrijven waardoor je de code niet twee keer hoeft te herhalen voor de uitzondering?

Laatste paar punten:

- Alle variabelen graag laten beginnen met een kleine letter. Ook wanneer je een nieuw object van een class aanmaakt.
- Vergeet geen commentaar boven code blokken zoals loops en if statements te zetten.

De opdracht was iets uitgebreider dan de uitwerking. Maar als je het bovenstaande nog kunt aanpassen, dan vind ik het goed.

**Comment by heartmates01** [comment]
volgensmij is het nu beter
